### ISSUE TITLE
entity User still has subclass Welcome in latest stable version  0.4.0 in  Nuget 

### ISSUE THREAD

**Issue by twiettwiet** [KoenZomers/TadoApi#3]
Using VS2019 Nuget KoenZomers.tado.api i found getMe() is broken because entity user seems empty.
This issue has been fixed in ealse committed on 4 May 2019 but not available in Nuget.

great work !

**Comment by KoenZomers** [comment]
Very well noticed @twiettwiet! Thanks for reporting this. Will release a new version in which this will be fixed.

**Comment by KoenZomers** [comment]
New version 0.4.0.1 has been released in which this has been addressed.

https://www.nuget.org/packages/KoenZomers.Tado.Api/0.4.0.1

Feel free to reopen this issue in case you feel it hasn't been fixed.
